### ISSUE TITLE
DNSClient possibly not thread safe

### ISSUE THREAD

**Issue by adam-fowler** [orlandos-nl/NioDNS#19]
It crashes in `DNSClient.send`. It looks like multiple threads can access `dnsDecoder.messageCache` at the same time. I got this crash with the following code
```swift
let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let client = try await DNSClient.connectTCP(
                    on: eventLoopGroup.next(),
                    host: "1.1.1.1"
                ).get()
async let result = client.initiateAAAAQuery(host: hostname, port: 0).get()
async let result2 = client.initiateAAAAQuery(host: hostname, port: 0).get()
async let result3 = client.initiateAAAAQuery(host: hostname, port: 0).get()
```

**Comment by JaapWijnen** [comment]
Thanks for the code example! I'll take a look

**Comment by JaapWijnen** [comment]
@adam-fowler I made sure the message cache is only accessed from the event loop in #20 . Could you check if this works as expected for your dns setup?

**Comment by adam-fowler** [comment]
That seems to have fixed the crash

**Comment by JaapWijnen** [comment]
Awesome, I had some trouble testing myself because the requests after my first were timing out. What did you use to test?

**Comment by adam-fowler** [comment]
@JaapWijnen There might be a problem. It seems to stall sometimes now

**Comment by Joannis** [comment]
Closing this, as the issue was elsewhere for that project.
