### ISSUE TITLE
package should be named swift-nio-dns

### ISSUE THREAD

**Issue by kelvin13** [orlandos-nl/NioDNS#22]
for consistency with other packages like `swift-nio`, `swift-nio-ssl`, this package should be renamed `swift-nio-dns` to follow swift package naming conventions.

**Comment by Joannis** [comment]
It's actually _against_ the naming conventions, because it's not an official Apple package. Formally it should be `DNSNIO`, but I hate that spelling too much.

**Comment by kelvin13** [comment]
valid
