### ISSUE TITLE
Minor fixes to support iOS targets (with packages that depend on it ex. MongoKitten & Meow).

### ISSUE THREAD

**Issue by furby-tm** [orlandos-nl/NioDNS#26]
Hey there,

These modifications are necessary to allow packages using **MongoKitten + Meow** to target iOS which otherwise would result in a failing build.

The modifications needed are as follows:

##### 1.) Useless variable, which is untyped, a build error.
https://github.com/Wabi-Studios/NioDNS/commit/f8c52ff6287b2935671bb0bff79429940ac6f70d 

##### 2.) Should **NIOTransportServices** be added as a dependency?
https://github.com/Wabi-Studios/NioDNS/commit/5e3b84b3c926e3b578befd69ceeffc7a50cd5fb3

**Comment by Joannis** [comment]
Thanks! Fixed and tagged.
